version: "3.7"

services:
  petclinic:
    container_name: petclinic-app
    image: 192.168.56.103:5000/petclinic-app
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgresDB:5432/petclinic
      - POSTGRES_USER=adnan
      - POSTGRES_PASS=abhadnan
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgresDB

  postgresDB:
    container_name: postgres_container
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=abhadnan
      - POSTGRES_USER=adnan
      - POSTGRES_DB=petclinic
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql1_db:/var/lib/postgresql/data

volumes:
  postgresql1_db:
