version: "3.7"

services:
  petclinic:
    container_name: petclinic-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgresDB:5432/petclinic
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresDB

  postgresDB:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
