# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "main" do |main|
    main.vm.box = "ubuntu/focal64"
    main.vm.hostname = 'main'

    main.vm.network "private_network", ip: "192.168.56.103"

    main.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.name = "ubuntu_main"
    end
  end

  config.vm.define "agent" do |agent|
    agent.vm.box = "ubuntu/focal64"
    agent.vm.hostname = 'agent'

    agent.vm.network "private_network", ip: "192.168.56.104"

    agent.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.name = "ubuntu-agent"
    end
  end
end
